[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_PRIVATE_TARGET = "server"

[[headers]]
for = "/api/*"
[headers.values]
"Cache-Control" = "no-store"
